services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    working_dir: /app
#    container_name: task_manager_api
#    ports:
#      - 3333:3333
#    restart: always
#    volumes:
#      - ./:/app/
#    command: ["sh", "-c", "chmod +x /app/auto.sh /app/buildrun.sh && /app/auto.sh"]

  db_postgres:
    container_name: task_manager_postgres_db
    image: postgres:13
    platform: linux/x86_64
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  db_mongo:
    container_name: mongo_db
    image: 'mongo:latest'
    build: .
    ports:
      - ${MONGO_DB_PORTS}
    environment:
      MONGO-INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASS}
    volumes:
      - ./_volume/mongo/logger/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
