services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: task_manager_api
    ports:
      - 3333:3333
    restart: always
    volumes:
      - ./:/app/
    command: ["sh", "-c", "chmod +x /app/auto.sh /app/buildrun.sh && /app/auto.sh"]

  db:
    container_name: task_manager_db
    image: postgres:13
    platform: linux/x86_64
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
